### PR TITLE
Use `@inlinable` and remove redundant helper function

### PR DESCRIPTION
**Pull request by nkristek**
This is a tiny PR that changes two things:
- Use `Dictionary(grouping:by:)` instead of the custom implementation that was used previously
- Set `@inlinable` instead of `@usableFromInline` on `internal` helper functions, that are small enough to benefit from inlining. This allows for better compiler optimisations, since the content of the inlined helper function can be inlined itself, instead of it just being able to be called from within an inlined function.
- Improve description of `Error.moveIsNotInTheSameSection` and `Error.adapterDoesNotContainSectionController`
- Fix snapshot tests in example project

### CODE REVIEW

**Review by Marcocanc — APPROVED** [review]

**Comment by Marcocanc** [comment]
@nkristek somehow the Unit Tests aren't running, potentially due to the force push. I also don't have the option to re-run on my end. Could you push something to retrigger the checks?

**Comment by nkristek** [comment]
@Marcocanc could you please retry running the workflow? I've pushed two small commits that improve the description of some error cases.

**Comment by nkristek** [comment]
I've just noticed, that in the example project the snapshot tests were broken. They're fixed as well now.

**Comment by Marcocanc** [comment]
Running now. I also changed the settings so you don't need approval for every run.

**Pull request merged**
